_wandb:
    value:
        cli_version: 0.25.0
        e:
            c9aov4h9kurwbta2mvwgmjken6qtflko:
                args:
                    - --config
                    - divnet_config.yaml
                    - --kfold
                codePath: divnet_train.py
                codePathLocal: divnet_train.py
                cpu_count: 64
                cpu_count_logical: 128
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "171798691840"
                        used: "141087064064"
                email: xfkwl00214xfkwl00214@gmail.com
                executable: /usr/bin/python3
                git:
                    commit: 2b8affd18b4dba328a0554c595a63c89b1e40da0
                    remote: https://github.com/otthree/divnet.git
                gpu: NVIDIA A100-PCIE-40GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-PCIE-40GB
                      uuid: GPU-88a3683e-e470-7c20-527f-15601be85d6f
                host: b9d8c7d0f4d9
                memory:
                    total: "540841746432"
                os: Linux-6.8.0-65-generic-x86_64-with-glibc2.39
                program: /workspace/divnet/divnet_train.py
                python: CPython 3.12.3
                root: /workspace/divnet
                startedAt: "2026-02-17T03:12:46.867282Z"
                writerId: c9aov4h9kurwbta2mvwgmjken6qtflko
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.3
            "5": 0.25.0
            "10":
                - 20
            "12": 0.25.0
            "13": linux-x86_64
cross_validation:
    value:
        k_folds: 5
data:
    value:
        batch_size: 2
        data_root: /workspace/pumpkinlab-storage-dhl
        num_workers: 4
        seed: 42
        test_ratio: 0.15
        train_ratio: 0.7
        val_batch_size: 1
        val_ratio: 0.15
fold:
    value: 0
model:
    value:
        dropout1: 0.5
        dropout2: 0.3
        num_classes: 3
        num_filters: 64
save:
    value:
        checkpoint_dir: ./checkpoints/divnet
training:
    value:
        early_stopping_patience: 20
        epochs: 100
        grad_clip: 1
        lr: 0.001
        lr_gamma: 0.1
        lr_milestones:
            - 30
            - 60
            - 80
        momentum: 0.9
        optimizer: SGD
        weight_decay: 0.0001
wandb:
    value:
        enabled: true
        project: DivNet AD Classification
